---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## nls.multstart

### Overview

__nls.multstart__ is an R package that allows more robust and reproducible fitting than ordinary nls or even nlsLM. These functions only allow a single starting value, meaning that it can be hard to get the best estimated model from a single set of starting values. This is especially true if the same model is wanting to be fitted over the levels of a factor.

__nls_multstart()__ is the main (currently only) function of __nls.multstart__. Similar to the R package __nls2__, it allows multiple starting values for each parameter and then tries multiple starting values on the data. The best model is then picked on AIC score. This results in a more reproducible and reliable method of fitting non-linear least squares regression in R.

This package is designed to work with the __tidyverse__, harnessing the functions within __broom__, __tidyr__, __dplyr__ and __purrr__ to extract estimates and plot things easily with __ggplot2__. A slightly less tidy-friendly implementation is [__nlsLoop__](https://github.com/padpadpadpad/nlsLoop)

### Issues and suggestions

Please report any issues/suggestions for improvement in the [issues link](https://github.com/padpadpadpad/nls.multstart/issues) for the repository. Or please email d.padfield@exeter.ac.uk.
